workflows:
  rocket-chat-workflow:
    name: rocket-chat Pipline
    scripts:
        - name: CICD Started
          script: echo "Welcome to CICD set up"
         
    publishing:
      email:
        recipients:
          - hello@iosacademy.io
